// Head-to-head results between battle teams (positions 4-12) from the 2025-26 season
// Source: basketball-reference.com, through Round 35

export interface H2HGame {
  home: string;
  away: string;
  homeScore: number;
  awayScore: number;
}

export const HEAD_TO_HEAD_RESULTS: H2HGame[] = [
  { home: "Hapoel Tel Aviv", away: "Barcelona", homeScore: 103, awayScore: 87 },
  { home: "Monaco", away: "Zalgiris", homeScore: 84, awayScore: 89 },
  { home: "Monaco", away: "Dubai", homeScore: 103, awayScore: 81 },
  { home: "Panathinaikos", away: "Barcelona", homeScore: 96, awayScore: 103 },
  { home: "Hapoel Tel Aviv", away: "Maccabi Tel Aviv", homeScore: 90, awayScore: 103 },
  { home: "Barcelona", away: "Valencia", homeScore: 108, awayScore: 102 },
  { home: "Maccabi Tel Aviv", away: "Barcelona", homeScore: 71, awayScore: 92 },
  { home: "Crvena Zvezda", away: "Zalgiris", homeScore: 88, awayScore: 79 },
  { home: "Valencia", away: "Hapoel Tel Aviv", homeScore: 93, awayScore: 100 },
  { home: "Dubai", away: "Barcelona", homeScore: 83, awayScore: 78 },
  { home: "Monaco", away: "Valencia", homeScore: 90, awayScore: 84 },
  { home: "Barcelona", away: "Zalgiris", homeScore: 73, awayScore: 88 },
  { home: "Hapoel Tel Aviv", away: "Monaco", homeScore: 85, awayScore: 77 },
  { home: "Panathinaikos", away: "Maccabi Tel Aviv", homeScore: 99, awayScore: 85 },
  { home: "Maccabi Tel Aviv", away: "Crvena Zvezda", homeScore: 92, awayScore: 99 },
  { home: "Valencia", away: "Dubai", homeScore: 80, awayScore: 78 },
  { home: "Monaco", away: "Panathinaikos", homeScore: 92, awayScore: 84 },
  { home: "Crvena Zvezda", away: "Panathinaikos", homeScore: 86, awayScore: 68 },
  { home: "Dubai", away: "Hapoel Tel Aviv", homeScore: 97, awayScore: 109 },
  { home: "Maccabi Tel Aviv", away: "Monaco", homeScore: 107, awayScore: 112 },
  { home: "Zalgiris", away: "Valencia", homeScore: 86, awayScore: 77 },
  { home: "Dubai", away: "Crvena Zvezda", homeScore: 102, awayScore: 86 },
  { home: "Crvena Zvezda", away: "Monaco", homeScore: 91, awayScore: 79 },
  { home: "Dubai", away: "Zalgiris", homeScore: 95, awayScore: 89 },
  { home: "Panathinaikos", away: "Dubai", homeScore: 103, awayScore: 82 },
  { home: "Valencia", away: "Crvena Zvezda", homeScore: 76, awayScore: 73 },
  { home: "Zalgiris", away: "Maccabi Tel Aviv", homeScore: 65, awayScore: 83 },
  { home: "Panathinaikos", away: "Valencia", homeScore: 79, awayScore: 89 },
  { home: "Crvena Zvezda", away: "Barcelona", homeScore: 79, awayScore: 89 },
  { home: "Dubai", away: "Maccabi Tel Aviv", homeScore: 95, awayScore: 97 },
  { home: "Hapoel Tel Aviv", away: "Crvena Zvezda", homeScore: 84, awayScore: 78 },
  { home: "Maccabi Tel Aviv", away: "Valencia", homeScore: 85, awayScore: 82 },
  { home: "Panathinaikos", away: "Hapoel Tel Aviv", homeScore: 93, awayScore: 82 },
  { home: "Zalgiris", away: "Panathinaikos", homeScore: 85, awayScore: 92 },
  { home: "Barcelona", away: "Monaco", homeScore: 74, awayScore: 90 },
  { home: "Hapoel Tel Aviv", away: "Zalgiris", homeScore: 80, awayScore: 93 },
  { home: "Barcelona", away: "Maccabi Tel Aviv", homeScore: 93, awayScore: 83 },
  { home: "Hapoel Tel Aviv", away: "Dubai", homeScore: 85, awayScore: 60 },
  { home: "Crvena Zvezda", away: "Valencia", homeScore: 89, awayScore: 106 },
  { home: "Valencia", away: "Monaco", homeScore: 92, awayScore: 101 },
  { home: "Zalgiris", away: "Crvena Zvezda", homeScore: 99, awayScore: 67 },
  { home: "Maccabi Tel Aviv", away: "Zalgiris", homeScore: 100, awayScore: 97 },
  { home: "Barcelona", away: "Dubai", homeScore: 91, awayScore: 89 },
  { home: "Monaco", away: "Crvena Zvezda", homeScore: 96, awayScore: 100 },
  { home: "Maccabi Tel Aviv", away: "Panathinaikos", homeScore: 75, awayScore: 71 },
  { home: "Valencia", away: "Maccabi Tel Aviv", homeScore: 94, awayScore: 83 },
  { home: "Crvena Zvezda", away: "Dubai", homeScore: 95, awayScore: 92 },
  { home: "Crvena Zvezda", away: "Hapoel Tel Aviv", homeScore: 87, awayScore: 75 },
  { home: "Zalgiris", away: "Monaco", homeScore: 104, awayScore: 87 },
  { home: "Hapoel Tel Aviv", away: "Valencia", homeScore: 99, awayScore: 104 },
  { home: "Crvena Zvezda", away: "Maccabi Tel Aviv", homeScore: 82, awayScore: 83 },
  { home: "Zalgiris", away: "Hapoel Tel Aviv", homeScore: 93, awayScore: 82 },
  { home: "Monaco", away: "Maccabi Tel Aviv", homeScore: 86, awayScore: 91 },
  { home: "Valencia", away: "Zalgiris", homeScore: 91, awayScore: 87 },
  { home: "Panathinaikos", away: "Zalgiris", homeScore: 92, awayScore: 88 },
  { home: "Barcelona", away: "Hapoel Tel Aviv", homeScore: 75, awayScore: 80 },
  { home: "Valencia", away: "Barcelona", homeScore: 62, awayScore: 66 },
  { home: "Panathinaikos", away: "Crvena Zvezda", homeScore: 82, awayScore: 74 },
  { home: "Dubai", away: "Panathinaikos", homeScore: 104, awayScore: 107 },
  { home: "Maccabi Tel Aviv", away: "Dubai", homeScore: 104, awayScore: 100 },
  { home: "Barcelona", away: "Crvena Zvezda", homeScore: 92, awayScore: 88 },
  { home: "Panathinaikos", away: "Monaco", homeScore: 107, awayScore: 97 },
  // Round 35
  { home: "Hapoel Tel Aviv", away: "Panathinaikos", homeScore: 92, awayScore: 88 },
  { home: "Zalgiris", away: "Barcelona", homeScore: 83, awayScore: 71 },
  { home: "Dubai", away: "Monaco", homeScore: 101, awayScore: 91 },
  // Round 36
  { home: "Zalgiris", away: "Dubai", homeScore: 65, awayScore: 77 },
  { home: "Barcelona", away: "Panathinaikos", homeScore: 79, awayScore: 93 },
];
